#!/usr/bin/env python3
"""Export a parity fixture the TypeScript tests assert against.

    python3 scripts/export_parity.py

Two implementations of the same mapping is exactly the situation where drift
hides. This writes Python's answers for a fixed set of inputs; the TS suite then
has to reproduce them. If either side changes behaviour, a test goes red rather
than the two quietly disagreeing.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from odu_core import all_odu, from_byte, spec_version  # noqa: E402
from odu_core.mnemonic import format_phrase, to_phrase  # noqa: E402

OUT = ROOT / "ts" / "test" / "fixtures" / "parity.json"

# Chosen to cover the awkward cases: empty input, a NUL byte, the high byte,
# multibyte UTF-8, and a payload longer than one figure's worth.
PAYLOADS = ["", "a", "Ifá", "heritage computing", "The quick brown fox", "\x00ÿ"]


def main() -> int:
    fixture = {
        "specVersion": spec_version(),
        "note": "Generated by scripts/export_parity.py — do not edit by hand.",
        "figures": [
            {"byte": b, "name": from_byte(b).name, "slug": from_byte(b).slug,
             "seniorityRank": from_byte(b).seniority_rank}
            for b in (0, 1, 15, 16, 44, 127, 128, 254, 255)
        ],
        "seniorityOrder": [o.byte for o in sorted(
            all_odu(), key=lambda o: o.seniority_rank)][:16],
        "phrases": {
            text: format_phrase(to_phrase(text.encode("utf-8")), "slug")
            for text in PAYLOADS
        },
    }

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        json.dumps(fixture, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    print(f"wrote {OUT.relative_to(ROOT)} — "
          f"{len(fixture['phrases'])} phrases, {len(fixture['figures'])} figures")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
